### PR TITLE
Automatic page view tracking

### PR DESCRIPTION
**Pull request by IeuanWalker**

### CODE REVIEW

**Comment by IeuanWalker** [comment]
@dhindrik  following on from my previous comment - https://github.com/dhindrik/TinyInsights.Maui/pull/14#issuecomment-2325211500

I've updated the code to use mauis built in `WeakEventManager` and that has the same issue as yours. On the first time returning to the MainPage it fires off the `OnAppearing` event, as it still has a subscriber - 
image

But on subsequent returns the `OnAppearing` event is triggered, but the `WeakEventManger` doesn't have any subscribers - 
image

Not really sure where to go from here tbh

**Comment by dhindrik** [comment]
Strange, seems like the Page object is handled by the GC, but in it can not be because it is possible to navigate back to ut. I mean when it still is in the navigation stack it should not be handled by the GC.

Will it be the same if you make the OnAppearing method static as in my example? 

An option for auto-tracking can also be to use Application.Current.PageAppearing. Maybe that is the preferred way over a handler? At least it is a more simple solution.

In that case we can create an Initialize method that we call from the both constructors. SendCrashes and AddMetaData can slo be moved to that method.
```csharp
public void Initialize()
{
     AddMetaData();
     Task.Run(SendCrashes);

     var weakHandler = new WeakEventHandler<Page>(OnAppearing);
    Application.Current.PageAppearing += weakHandler.Handler;
}

private static void OnAppearing(object sender, Page e)
{
 //TrackPageView
}
```

What do you think?

I also have to say that I really appreciate your work with the library!

**Comment by IeuanWalker** [comment]
@dhindrik  No prob, its a really cool project.

I've implemented you suggestion here, on a separate branch (just for testing) - https://github.com/IeuanWalker/TinyInsights.Maui/blob/6505e96d47d447ee975f30223febf8a0c4821f40/TinyInsights/ApplicationInsightsProvider.cs#L107C5-L111C6

The static `OnAppearing` method seems to work completely fine. Im just not sure how to call the  `TrackPageViewAsync` method from within the static method.

If I make it a non static method it never gets triggered

**Comment by dhindrik** [comment]
What do you think of adding a static field for the instance of the provider? The extension sets it as a singleton, so it should not be a problem. 

`private static ApplicationInsightsProvider instance;`

It is ok to remove the ILogger stuff from the sample project, I also noticed that it makes it harder to debug. And I guess it is not the primary way to use the library. I am not using it in my apps. If some people want to read about it, they can read the docs.

**Comment by IeuanWalker** [comment]
@dhindrik Ye that works.

Think this PR is ready now, I've left ILogger on the sample project. The static `IsInitialized` variable i added, avoided any issue i was having with it.

**Comment by dhindrik** [comment]
Great work! Thank you very much.

**Pull request merged**
